# Generated by Django 4.2.3 on 2023-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('narx_sana', models.DateField()),
                ('muallif', models.CharField(max_length=300)),
                ('olchami', models.CharField(max_length=50)),
                ('nashriyot', models.CharField(max_length=300)),
                ('sana', models.DateField()),
                ('hajm', models.PositiveIntegerField()),
                ('muqova', models.CharField(max_length=50)),
                ('hilol_nashr', models.IntegerField(blank=True, null=True)),
                ('qamarbooks', models.IntegerField(blank=True, null=True)),
                ('azonkitoblari', models.IntegerField(blank=True, null=True)),
                ('asaxiy_book', models.IntegerField(blank=True, null=True)),
                ('bookuzbekistan', models.IntegerField(blank=True, null=True)),
                ('ibookuz', models.IntegerField(blank=True, null=True)),
                ('zumarbooks', models.IntegerField(blank=True, null=True)),
                ('shamskitoblari', models.IntegerField(blank=True, null=True)),
                ('golden_books', models.IntegerField(blank=True, null=True)),
                ('marifat_uyi2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
