# Generated by Django 4.2.3 on 2023-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0002_kitob_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AddField(
            model_name='kitob',
            name='tarif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
