# Generated by Django 4.2.3 on 2023-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0003_alter_kitob_options_kitob_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='hilol_nashr',
            field=models.IntegerField(blank=True, default='mavjud emas', null=True),
        ),
    ]
