# Generated by Django 4.2.3 on 2023-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0004_alter_kitob_hilol_nashr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='asaxiy_book',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='azonkitoblari',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='bookuzbekistan',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='golden_books',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='hilol_nashr',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='ibookuz',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='marifat_uyi2',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='qamarbooks',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='shamskitoblari',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='zumarbooks',
        ),
        migrations.AddField(
            model_name='kitob',
            name='dokonlar',
            field=models.TextField(null=True),
        ),
    ]
